"""
Django settings for investimentos project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from sloth.conf.settings import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0r!s%*0ihfgps69&pv+s+h4j&v)5h*ru64t7botju(0qc0+cc='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'investimentos',
    'oauth2_provider',
    'sloth.api',
    'sloth.app',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'investimentos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sloth.core.views.context_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'investimentos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'investimentos',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '5432'
    }
}


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ALLOWED_HOSTS = ['*']
BASE_DIR = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


SLOTH = {
    'NAME': 'COLETA SETEC',
    'ICON': None,
    'FAVICON': '/static/images/govbr-16x16.png',
    'VERSION': 1.0,
	'LOGIN': {
		'LOGO': None,
		'TITLE': 'COLETA SETEC',
		'TEXT': 'Sistema de Coleta de Demandas da Rede Federal de Educação Profissional, Científica e Tecnológica',
		'IMAGE': '/static/images/public.png',
	},
	'HEADER': {
		'LOGO': None,
		'TITLE': 'COLETA SETEC',
		'TEXT': None,
	},
	'FOOTER': {
		'TITLE': '© 2022 Ministério da Educação',
		'TEXT': 'Todos os direitos reservados',
		'LINKS': [],
	},
	'INCLUDE': {
		'CSS': ['/static/css/investimentos.css'],
		'JS': ['/static/js/investimentos.js'],
	}
}

