# Generated by Django 4.1 on 2023-03-28 12:41

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0002_administrador_user_gestor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.ciclo', verbose_name='Ciclo')),
                ('instituicao', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.instituicao', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.AddField(
            model_name='demanda',
            name='solicitacao',
            field=sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investimentos.solicitacao', verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='questionariofinal',
            name='solicitacao',
            field=sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='investimentos.solicitacao', verbose_name='Solicitação'),
        ),
    ]
