# Generated by Django 4.1 on 2023-03-28 12:41

from django.db import migrations


def migrate(apps, editor):
    Solicitacao = apps.get_model('investimentos.Solicitacao')

    Demanda = apps.get_model('investimentos.Demanda')
    for demanda in Demanda.objects.all():
        solicitacao = Solicitacao.objects.get_or_create(
            instituicao=demanda.instituicao, ciclo=demanda.ciclo
        )[0]
        demanda.solicitacao = solicitacao
        demanda.save()

    QuestionarioFinal = apps.get_model('investimentos.QuestionarioFinal')
    for questionario in QuestionarioFinal.objects.all():
        solicitacao = Solicitacao.objects.get_or_create(
            instituicao=questionario.instituicao, ciclo=questionario.ciclo
        )[0]
        questionario.solicitacao = solicitacao
        questionario.save()

def unmigrate(apps, editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0003_solicitacao_demanda_solicitacao'),
    ]

    operations = [
        migrations.RunPython(migrate, unmigrate)
    ]
