# Generated by Django 4.1 on 2023-03-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0004_auto_20230328_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questionariofinal',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='questionariofinal',
            name='instituicao',
        ),
    ]
