# Generated by Django 4.1 on 2023-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0007_questionariofinal_prioridade_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='notificado',
            field=models.BooleanField(default=False, verbose_name='Notificado'),
        ),
    ]
