# Generated by Django 4.1 on 2023-04-02 06:54

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0008_gestor_notificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='ano',
            field=sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investimentos.ano', verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='duvida',
            name='ano',
            field=sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investimentos.ano', verbose_name='Ano'),
        ),
    ]
