# Generated by Django 4.1 on 2022-09-29 05:12

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('renderers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=sloth.db.models.CharField(default=None, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
