# Generated by Django 3.2.8 on 2021-10-21 08:26

from django.db import migrations, models
import django.db.models.deletion
import dms2


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='naturalidade',
            field=dms2.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.municipio', verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='endereco',
            field=dms2.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.endereco', verbose_name='Endereço'),
        ),
    ]
