# Generated by Django 4.0.4 on 2022-04-16 06:46

from django.db import migrations, models
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_servidor_user_alter_estado_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='None')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
