# Generated by Django 3.2.8 on 2021-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211021_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='cidades_metropolitanas',
            field=models.ManyToManyField(blank=True, related_name='s1', to='base.Municipio', verbose_name='Cidades Metropolitanas'),
        ),
    ]
