# Generated by Django 3.2.8 on 2021-11-03 10:15

from django.db import migrations
import django.db.models.deletion
import dms2.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_estado_cidades_metropolitanas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='estado',
            name='endereco',
            field=dms2.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.endereco'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='endereco',
            field=dms2.db.models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.endereco', verbose_name='Endereço'),
        ),
    ]
