# Generated by Django 3.2.8 on 2021-11-03 10:16

from django.db import migrations
import django.db.models.deletion
import dms2.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211103_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='endereco',
            field=dms2.db.models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.endereco'),
        ),
    ]
