# Generated by Django 3.2.8 on 2021-11-03 14:54

from django.db import migrations
import django.db.models.deletion
import dms2.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_estado_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='endereco',
            field=dms2.db.models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.endereco', verbose_name='Endereço'),
        ),
    ]
