# Generated by Django 3.2.8 on 2021-11-04 08:57

from django.db import migrations, models
import dms2.base
import dms2.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_estado_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.PositiveIntegerField(verbose_name='DDD')),
                ('numero', dms2.db.models.CharField(max_length=255, verbose_name='Número')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dms2.base.ModelMixin),
        ),
        migrations.AddField(
            model_name='estado',
            name='telefones',
            field=dms2.db.models.OneToManyField(to='base.Telefone', verbose_name='Telefones'),
        ),
    ]
