# Generated by Django 3.2.8 on 2021-11-05 06:02

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import dms2.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_auto_20211104_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefone',
            options={'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
        migrations.AddField(
            model_name='servidor',
            name='user',
            field=dms2.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
