# Generated by Django 3.2.8 on 2021-11-05 07:00

from django.db import migrations, models
import django.db.models.deletion
import dms2.base
import dms2.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211105_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', dms2.db.models.CharField(max_length=255, verbose_name='Sigla')),
                ('reitor', dms2.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.servidor', verbose_name='Reitor')),
            ],
            options={
                'verbose_name': 'Instituto',
                'verbose_name_plural': 'Instituto',
            },
            bases=(models.Model, dms2.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='UnidadeOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', dms2.db.models.CharField(max_length=255, verbose_name='Sigla')),
                ('diretor', dms2.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.servidor', verbose_name='Diretor')),
                ('instituto', dms2.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.instituto', verbose_name='Instituto')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
            bases=(models.Model, dms2.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', dms2.db.models.CharField(max_length=255, verbose_name='Sigla')),
                ('chefe', dms2.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefia', to='base.servidor', verbose_name='Chefe')),
                ('uo', dms2.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.unidadeorganizacional', verbose_name='Campus')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setor',
            },
            bases=(models.Model, dms2.base.ModelMixin),
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor',
            field=dms2.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.setor', verbose_name='Setor'),
        ),
    ]
