# Generated by Django 3.2.8 on 2021-11-05 12:09

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import dms2.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_auto_20211105_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='reitor',
            field=dms2.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.servidor', verbose_name='Reitor'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='setor',
            field=dms2.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='user',
            field=dms2.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='chefe',
            field=dms2.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefia', to='base.servidor', verbose_name='Chefe'),
        ),
        migrations.AlterField(
            model_name='unidadeorganizacional',
            name='diretor',
            field=dms2.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.servidor', verbose_name='Diretor'),
        ),
    ]
