# Generated by Django 3.2.8 on 2021-11-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20211105_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='substitutos_eventuais',
            field=models.ManyToManyField(blank=True, related_name='substituicao_chefia', to='base.Servidor', verbose_name='Substituto Eventuais'),
        ),
    ]
