# Generated by Django 3.2.8 on 2021-11-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms2', '0002_auto_20211105_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scope_key',
            field=models.CharField(max_length=50, null=True, verbose_name='Chave do Escopo'),
        ),
        migrations.AlterField(
            model_name='role',
            name='scope_value',
            field=models.IntegerField(null=True, verbose_name='Valor do Escopo'),
        ),
    ]
