# Generated by Django 3.2.8 on 2021-11-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dms2', '0004_auto_20211105_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scope_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo do Escopo'),
        ),
    ]
