# Generated by Django 3.2.8 on 2021-11-08 23:33

from django.db import migrations, models
import django.db.models.deletion
import sloth.base
import sloth.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
            bases=(models.Model, sloth.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('categoria', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
            },
            bases=(models.Model, sloth.base.ModelMixin),
        ),
    ]
