# Generated by Django 3.2.8 on 2021-11-25 18:39

from django.db import migrations, models
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', sloth.db.models.CharField(choices=[['Administrador', 'Administrador'], ['Gestor', 'Gestor']], max_length=255, verbose_name='Perfil')),
                ('introducao', models.TextField(verbose_name='Introdução')),
                ('detalhamento', models.TextField(verbose_name='Detalhamento')),
            ],
            options={
                'verbose_name': 'Mensagem Inicial',
                'verbose_name_plural': 'Mensagens Iniciais',
                'icon': 'chat-left-text',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
