# Generated by Django 3.2.8 on 2021-11-09 00:27

from django.db import migrations, models
import django.db.models.deletion
import sloth.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0002_campus_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', sloth.db.models.CharField(max_length=255, verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Ano',
                'verbose_name_plural': 'Anos',
            },
            bases=(models.Model, sloth.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Prioridade',
                'verbose_name_plural': 'Prioridades',
            },
            bases=(models.Model, sloth.base.ModelMixin),
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campi'},
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Início')),
                ('fim', models.DateField(verbose_name='Fim')),
                ('teto', sloth.db.models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Teto (R$)')),
                ('ano', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.ano', verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Ciclo de Demanda',
                'verbose_name_plural': 'Ciclos de Demandas',
            },
            bases=(models.Model, sloth.base.ModelMixin),
        ),
    ]
