# Generated by Django 3.2.8 on 2021-11-08 22:38

from django.db import migrations, models
import django.db.models.deletion
import sloth.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0003_auto_20211109_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='prioridades',
            field=models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]], default=4, verbose_name='Prioridades'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', sloth.db.models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor (R$)')),
                ('ciclo', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.ciclo', verbose_name='Ciclo')),
                ('classificacao', sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investimentos.subcategoria', verbose_name='Classificação')),
                ('instituicao', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.instituicao', verbose_name='Instituição')),
                ('prioridade', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.prioridade', verbose_name='Prioridade')),
            ],
            options={
                'verbose_name': 'Ciclo de Demanda',
                'verbose_name_plural': 'Ciclos de Demandas',
                'fieldsets': {'Dados Gerais': ('ciclo', 'instituicao')},
            },
            bases=(models.Model, sloth.base.ModelMixin),
        ),
    ]
