# Generated by Django 3.2.8 on 2021-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0003_auto_20211227_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionariofinal',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
