# Generated by Django 3.2.8 on 2021-11-08 22:58

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0004_auto_20211108_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demanda',
            options={'verbose_name': 'Demanda', 'verbose_name_plural': 'Demandas'},
        ),
        migrations.AlterField(
            model_name='demanda',
            name='valor',
            field=sloth.db.models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Valor (R$)'),
        ),
    ]
