# Generated by Django 3.2.8 on 2021-12-27 17:04

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0005_auto_20211227_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='valor_total',
            field=sloth.db.models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Valor Total (R$)'),
        ),
    ]
