# Generated by Django 3.2.8 on 2021-12-27 17:08

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0006_demanda_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='teto',
            field=sloth.db.models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Limite de Investimento por Instituição (R$)'),
        ),
    ]
