# Generated by Django 3.2.8 on 2021-11-09 07:02

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0007_auto_20211109_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntaquestionario',
            name='questionario',
            field=sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.questionario', verbose_name='Questionário'),
        ),
    ]
