# Generated by Django 3.2.8 on 2021-12-27 17:29

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0008_notificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='cpf',
        ),
        migrations.AddField(
            model_name='gestor',
            name='email',
            field=sloth.db.models.CharField(max_length=255, null=True, verbose_name='E-mail'),
        ),
    ]
