# Generated by Django 3.2.8 on 2021-11-09 10:33

from django.db import migrations, models
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0008_alter_perguntaquestionario_questionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perguntaquestionario',
            options={'verbose_name': 'Pergunta de Questionário', 'verbose_name_plural': 'Perguntas de Questionário'},
        ),
        migrations.AddField(
            model_name='ciclo',
            name='instituicoes',
            field=models.ManyToManyField(blank=True, to='investimentos.Instituicao', verbose_name='Instituições'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=sloth.db.models.CharField(max_length=255, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_resposta',
            field=models.IntegerField(choices=[[1, 'Texto Curto'], [2, 'Texto Longo'], [3, 'Número Decimal'], [4, 'Número Inteiro'], [5, 'Data'], [6, 'Sim/Não'], [7, 'Múltiplas Escolhas']], verbose_name='Tipo de Resposta'),
        ),
    ]
