# Generated by Django 3.2.8 on 2021-12-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0009_auto_20211227_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='sigla',
        ),
    ]
