# Generated by Django 3.2.8 on 2021-11-09 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investimentos', '0009_auto_20211109_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', sloth.db.models.CharField(max_length=255, verbose_name='CPF')),
                ('instituicao', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.instituicao', verbose_name='Instituição')),
                ('user', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Gestor ',
                'verbose_name_plural': 'Gestores',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', sloth.db.models.CharField(max_length=255, verbose_name='CPF')),
                ('user', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Administrador ',
                'verbose_name_plural': 'Administradores',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
