# Generated by Django 3.2.8 on 2021-12-28 16:20

from django.db import migrations, models
import sloth.core.base


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0010_remove_campus_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('data_pergunta', models.DateTimeField(verbose_name='Data da Pergunta')),
                ('resposta', models.TextField(null=True, verbose_name='Resposta')),
                ('data_resposta', models.DateTimeField(null=True, verbose_name='Data da Resposta')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'icon': 'exclamation-square',
                'add_form': 'DuvidaForm',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='fim',
            field=models.DateField(verbose_name='Fim da Exibição'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='inicio',
            field=models.DateField(verbose_name='Início da Exibição'),
        ),
    ]
