# Generated by Django 3.2.8 on 2021-11-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0011_auto_20211110_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria de Investimento', 'verbose_name_plural': 'Categorias de Investimento'},
        ),
        migrations.AddField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(default='Descrição da demanda', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
