# Generated by Django 3.2.8 on 2021-12-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0012_auto_20211228_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclo',
            options={'verbose_name': 'Ciclo de Demandas', 'verbose_name_plural': 'Ciclos de Demandas'},
        ),
    ]
