# Generated by Django 3.2.8 on 2021-11-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0012_auto_20211110_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perguntaquestionario',
            options={'verbose_name': 'Resposta de Questionário', 'verbose_name_plural': 'Respostas de Questionário'},
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='instituicoes',
            field=models.ManyToManyField(blank=True, to='investimentos.Instituicao', verbose_name='Demandantes'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='prioridades',
            field=models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]], verbose_name='Quantidade'),
        ),
    ]
