# Generated by Django 3.2.8 on 2022-01-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0013_alter_ciclo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='contabilizar',
            field=models.BooleanField(default=True, help_text='Debitar no limite de investimento quando uma solicitação for realizada.', verbose_name='Contatilizar'),
        ),
    ]
