# Generated by Django 3.2.8 on 2021-11-17 06:16

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0013_auto_20211110_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='classificacao',
            field=sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investimentos.categoria', verbose_name='Classificação'),
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
