# Generated by Django 3.2.8 on 2021-11-17 06:27

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0014_auto_20211117_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('classificacao', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.categoria', verbose_name='Classificação')),
            ],
            options={
                'verbose_name': 'Limite de Demanda',
                'verbose_name_plural': 'Limites de Demanda',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='limites',
            field=sloth.db.models.OneToManyField(to='investimentos.LimiteDemanda', verbose_name='Limites de Demanda'),
        ),
    ]
