# Generated by Django 3.2.8 on 2022-01-06 22:13

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0015_pergunta_pre_requisito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='resposta_pre_requisito',
            field=sloth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Resposta do Pré-Requisito'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='pre_requisito',
            field=sloth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investimentos.pergunta', verbose_name='Pergunta Pré-Requisito'),
        ),
    ]
