# Generated by Django 3.2.8 on 2021-11-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0015_auto_20211117_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='prioridades',
        ),
    ]
