# Generated by Django 3.2.8 on 2022-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0017_auto_20220107_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='ordem',
            field=models.IntegerField(null=True, verbose_name='Ordem'),
        ),
    ]
