# Generated by Django 3.2.8 on 2021-11-17 13:50

from django.db import migrations, models
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0017_auto_20211117_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='ano',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='descricao',
            field=sloth.db.models.CharField(default='Teste', max_length=255, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='fim',
            field=models.DateField(verbose_name='Data de Fim das Solicitações'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='inicio',
            field=models.DateField(verbose_name='Data de Início das Solicitações'),
        ),
    ]
