# Generated by Django 3.2.8 on 2022-01-19 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investimentos', '0018_pergunta_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='notificados',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Notificados'),
        ),
    ]
