# Generated by Django 3.2.8 on 2021-11-19 19:45

from django.db import migrations, models
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0018_auto_20211117_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclo',
            options={'verbose_name': 'Ciclo de Solicitação de Investimento', 'verbose_name_plural': 'Ciclos de Solicitação de Investimento'},
        ),
        migrations.AlterModelOptions(
            name='perguntaquestionario',
            options={'verbose_name': 'Resposta de Questionário', 'verbose_name_plural': 'Respostas dos Questionário'},
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='fim',
            field=models.DateField(verbose_name='Fim das Solicitações'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='inicio',
            field=models.DateField(verbose_name='Início das Solicitações'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='instituicoes',
            field=models.ManyToManyField(blank=True, help_text='Não informar, caso deseje incluir todas as instituições.', to='investimentos.Instituicao', verbose_name='Demandantes'),
        ),
        migrations.AlterField(
            model_name='opcaoresposta',
            name='nome',
            field=sloth.db.models.CharField(max_length=255, verbose_name='Resposta'),
        ),
    ]
