# Generated by Django 3.2.8 on 2022-01-19 06:56

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0019_mensagem_notificados'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionariofinal',
            name='prioridade_1',
            field=sloth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r1', to='investimentos.demanda', verbose_name='Prioridade 1'),
        ),
        migrations.AddField(
            model_name='questionariofinal',
            name='prioridade_2',
            field=sloth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r2', to='investimentos.demanda', verbose_name='Prioridade 2'),
        ),
        migrations.AddField(
            model_name='questionariofinal',
            name='prioridade_3',
            field=sloth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r3', to='investimentos.demanda', verbose_name='Prioridade 3'),
        ),
    ]
