# Generated by Django 3.2.8 on 2022-03-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0022_auto_20220209_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='user',
        ),
    ]
