# Generated by Django 4.0.3 on 2022-04-15 06:30

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='user',
        ),
        migrations.AlterField(
            model_name='estado',
            name='endereco',
            field=sloth.db.models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.endereco', verbose_name='Endereço'),
        ),
    ]
