# Generated by Django 4.0.4 on 2022-05-17 18:20

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gerente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerente',
            options={'verbose_name': 'Gerente', 'verbose_name_plural': 'Gerentes'},
        ),
        migrations.AddField(
            model_name='estado',
            name='historia',
            field=sloth.db.models.TextField(default='', verbose_name='História'),
            preserve_default=False,
        ),
    ]
