# Generated by Django 4.0.4 on 2022-05-28 11:01

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_gerente_options_estado_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='cidades_metropolitanas',
            field=sloth.db.models.ManyToManyField(blank=True, related_name='s1', to='base.municipio', verbose_name='Cidades Metropolitanas'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cpf',
            field=sloth.db.models.BrCpfField(max_length=255, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='substitutos_eventuais',
            field=sloth.db.models.ManyToManyField(blank=True, related_name='substituicao_chefia', to='base.servidor', verbose_name='Substituto Eventuais'),
        ),
    ]
