# Generated by Django 4.0.4 on 2022-04-22 12:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('foto', models.ImageField(upload_to='animais', verbose_name='Foto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_cadastro', models.DateField(default=datetime.datetime.today, verbose_name='Data do Cadastro')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'fieldsets': {'Dados Gerais', (('nome', 'tipo'), 'foto', 'data_cadastro', 'descricao', 'proprietario')},
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='None')),
                ('cpf', sloth.db.models.CharField(max_length=255, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', sloth.db.models.CharField(max_length=255, verbose_name='Descrição')),
                ('contagiosa', models.BooleanField(verbose_name='Contagiosa')),
            ],
            options={
                'verbose_name': 'Doença',
                'verbose_name_plural': 'Doenças',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='None')),
                ('cpf', sloth.db.models.CharField(max_length=255, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', sloth.db.models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Animal',
                'verbose_name_plural': 'Tipos de Animais',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='TipoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', sloth.db.models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', sloth.db.models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tipo de Procedimento',
                'verbose_name_plural': 'Tipos de Procedimento',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(null=True, verbose_name='Data de Término')),
                ('eficaz', models.BooleanField(null=True, verbose_name='Eficaz')),
                ('animal', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.animal', verbose_name='Animal')),
                ('doenca', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.doenca', verbose_name='Doença')),
            ],
            options={
                'verbose_name': 'Tratamento',
                'verbose_name_plural': 'Tratamentos',
                'fieldsets': {'Dados Gerais': (('animal', 'doenca'), ('data_inicio', 'data_fim')), 'Resultado': ('eficaz',)},
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data/Hora')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('tipo', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.tipoprocedimento', verbose_name='Tipo')),
                ('tratamento', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.tratamento', verbose_name='Tratamento')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'fieldsets': {'Dados Gerais': ('tratamento', ('tipo', 'data_hora')), 'Outras Informações': ('observacao',)},
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.AddField(
            model_name='animal',
            name='proprietario',
            field=sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.cliente', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.tipoanimal', verbose_name='Tipo'),
        ),
    ]
