# Generated by Django 4.0.4 on 2022-06-05 07:11

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_tipoprocedimento_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=sloth.db.models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='observacao',
            field=sloth.db.models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
