# Generated by Django 4.1 on 2022-09-26 18:52

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255)),
                ('funcionarios', sloth.db.models.ManyToManyField(related_name='lojas', to='papeis.funcionario')),
                ('gerente', sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='papeis.funcionario')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255)),
                ('loja', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papeis.loja')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.AddField(
            model_name='loja',
            name='rede',
            field=sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papeis.rede'),
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255)),
                ('rede', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papeis.rede')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
