# Generated by Django 4.0.4 on 2022-05-11 16:45

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_application_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('start', models.DateTimeField(auto_now=True, verbose_name='Início')),
                ('end', models.DateTimeField(null=True, verbose_name='Fim')),
                ('progress', models.IntegerField(default=0, verbose_name='Progresso')),
                ('message', models.IntegerField(null=True, verbose_name='Mensagem')),
                ('error', models.TextField(null=True, verbose_name='Erro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
