# Generated by Django 4.0.4 on 2022-05-12 09:44

from django.db import migrations, models
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_stopped_alter_task_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo', blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=sloth.db.models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='role',
            name='scope_key',
            field=sloth.db.models.CharField(max_length=50, null=True, verbose_name='Escopo', blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='scope_type',
            field=sloth.db.models.CharField(db_index=True, max_length=50, null=True, verbose_name='Tipo do Escopo', blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='scope_value',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Valor do Escopo', blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=sloth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.user', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=sloth.db.models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='task',
            name='message',
            field=sloth.db.models.CharField(max_length=255, null=True, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=sloth.db.models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Usuário'),
        ),
    ]
