# Generated by Django 4.0.4 on 2022-05-17 18:20

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_role_active_alter_role_name_alter_role_scope_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='description',
            field=sloth.db.models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='task',
            name='error',
            field=sloth.db.models.TextField(null=True, verbose_name='Erro'),
        ),
    ]
