# Generated by Django 4.0.4 on 2022-06-19 11:52

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_application_available_scopes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.JSONField(verbose_name='Dados da Inscrição')),
                ('user', sloth.db.models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_notification', to='api.user', verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
