# Generated by Django 4.1 on 2023-04-12 20:49

from django.db import migrations, models
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_task_partial_task_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Remetente')),
                ('to', sloth.db.models.TextField(help_text='Separar endereços de e-mail por ",".', verbose_name='Destinatário')),
                ('subject', sloth.db.models.CharField(max_length=255, verbose_name='Assunto')),
                ('content', sloth.db.models.TextField(verbose_name='Conteúdo')),
                ('sent_at', models.DateTimeField(null=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mails',
                'icon': 'mail',
                'fieldsets': {'Dados Gerais': ('from_email', 'subject', 'to'), 'Detalhamento': ('content',)},
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
