# Generated by Django 4.0.4 on 2022-05-01 13:53

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='nome',
            field=sloth.db.models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
