# Generated by Django 4.0.4 on 2022-05-01 15:04

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0004_escola_coordenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('escola', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.escola', verbose_name='Escola')),
                ('serie', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.serie')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
