# Generated by Django 4.0.4 on 2022-05-01 16:26

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0005_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos', verbose_name='Foto')),
                ('escola', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.escola', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'icon': 'person',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='simulado.aluno', verbose_name='Alunos'),
        ),
    ]
