# Generated by Django 4.0.4 on 2022-05-01 17:03

from django.db import migrations, models
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0006_aluno_turma_alunos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perguntas', verbose_name='Imagem')),
                ('alternativa_a', sloth.db.models.CharField(max_length=255, verbose_name='a)')),
                ('alternativa_b', sloth.db.models.CharField(max_length=255, verbose_name='b)')),
                ('alternativa_c', sloth.db.models.CharField(max_length=255, verbose_name='c)')),
                ('alternativa_d', sloth.db.models.CharField(max_length=255, verbose_name='d)')),
                ('resposta', sloth.db.models.CharField(choices=[['a', 'a'], ['b', 'b'], ['c', 'c'], ['d', 'd']], max_length=255, verbose_name='Resposta')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'icon': 'question-square',
                'fieldsets': {'Alternativas': ('alternativa_a', 'alternativa_b', 'alternativa_c', 'alternativa_d'), 'Dados Gerais': ('enunciado', 'imagem'), 'Gabarito': ('resposta', 'justificativa')},
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
