# Generated by Django 4.0.4 on 2022-05-01 17:54

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0007_pergunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('alunos', models.ManyToManyField(to='simulado.aluno', verbose_name='Alunos')),
            ],
            options={
                'verbose_name': 'Agendamento de Simulado',
                'verbose_name_plural': 'Agendamentos de Simulado',
                'icon': 'clock-history',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='resposta',
            field=sloth.db.models.CharField(choices=[['A', 'A'], ['B', 'B'], ['C', 'C'], ['D', 'D']], max_length=255, verbose_name='Resposta'),
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.IntegerField(default=0, verbose_name='Progresso')),
                ('agendamento', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.agendamento', verbose_name='Agendamento')),
                ('aluno', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Agendamento de Simulado',
                'verbose_name_plural': 'Agendamentos de Simulado',
                'icon': 'list-ul',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', sloth.db.models.CharField(max_length=255, verbose_name='Resposta')),
                ('correta', models.BooleanField(null=True, verbose_name='Correta')),
                ('pergunta', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_alunos', to='simulado.pergunta', verbose_name='Pergunta')),
                ('simulado', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.simulado', verbose_name='Simulado')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='perguntas',
            field=models.ManyToManyField(to='simulado.pergunta', verbose_name='Perguntas'),
        ),
    ]
